### ISSUE TITLE
Handler doesn't fire when clicking on another component using onclick-outside

### ISSUE THREAD

**Issue by frankdugan3** [egoist/onclick-outside#1]
I'm using `onclick-outside` with Vue 2.0.3.

If I use `onclick-outside` in separate or reoccurring components, the handler will only fire if I click on an element or component that does not use `onclick-outside` at all.

I couldn't find a CDN source to create a JS Fiddle, but if you know of one I could easily make a repro. Or I could create a quick gist if you prefer.

**Comment by egoist** [comment]
You can use the umd version to make a repro https://unpkg.com/onclick-outside@0.1.1/index.js

**Comment by frankdugan3** [comment]
OK, I've figured out my problem. Inside the `onclick-outside` component, I had some nested elements that used `v-if`. It appears that under certain conditions, this can prevent any click event from firing in all `onclick-outside` components (perhaps because the target disappears from the DOM?). In any case, switching those elements to use `v-for` solved my problem. I'm going to close this since I wasn't able to come up with a simple repro.
